const express = require('express');
const { createHash, randomBytes } = require('node:crypto');
const supabase = require('../config/supabase');
const authenticateUser = require('../middleware/auth');
const { requireCapability } = require('../middleware/authorization');
const router = express.Router();
const roles = ['lead_pastor','care','ministry','finance','check_in','content'];
const capabilities = ['people.read','people.write','care.read','care.confidential','care.write','finance.read','finance.write','check_in.read','check_in.write','check_in.override','events.read','events.write','volunteers.read','volunteers.write','communications.read','communications.write','content.read','content.write','staff.manage','audit.read','organization.export'];
const hash = (token) => createHash('sha256').update(token).digest('hex');

router.get('/:congregationId', authenticateUser, requireCapability('staff.manage'), async (req,res,next) => { try {
  const [{data:memberships,error},{data:campuses,error:campusError},{data:invitations,error:inviteError},{data:overrides,error:overrideError}] = await Promise.all([
    supabase.from('organization_memberships').select('id,user_id,role,campus_id,active,created_at').eq('congregation_id',req.congregationId).order('created_at'),
    supabase.from('campuses').select('id,name').eq('congregation_id',req.congregationId).order('name'),
    supabase.from('staff_invitations').select('id,email,role,campus_id,expires_at,accepted_at,created_at').eq('congregation_id',req.congregationId).order('created_at',{ascending:false}),
    supabase.from('capability_overrides').select('membership_id,capability,allowed'),
  ]); if(error)throw error;if(campusError)throw campusError;if(inviteError)throw inviteError;if(overrideError)throw overrideError;
  const users=await Promise.all(memberships.map(async(membership)=>{const {data}=await supabase.auth.admin.getUserById(membership.user_id);return {...membership,email:data.user?.email||null,overrides:overrides.filter(item=>item.membership_id===membership.id)};}));
  res.json({data:{memberships:users,campuses,invitations,roles,capabilities}});
} catch(error){next(error);} });

router.post('/:congregationId/campuses', authenticateUser, requireCapability('staff.manage'), async(req,res,next)=>{try{const name=String(req.body?.name||'').trim();if(name.length<2)return res.status(400).json({error:{code:'CAMPUS_NAME_REQUIRED',message:'Campus name is required.',requestId:req.requestId}});const {data,error}=await supabase.from('campuses').insert({congregation_id:req.congregationId,name}).select('id,name').single();if(error)throw error;await supabase.from('audit_events').insert({congregation_id:req.congregationId,actor_user_id:req.user.id,action:'campus.created',resource_type:'campus',resource_id:String(data.id),request_id:req.requestId});res.status(201).json({data});}catch(error){next(error);}});

router.post('/:congregationId/invitations', authenticateUser, requireCapability('staff.manage'), async(req,res,next)=>{try{const email=String(req.body?.email||'').trim().toLowerCase();const role=req.body?.role;const campusId=req.body?.campusId||null;if(!/^\S+@\S+\.\S+$/.test(email)||!roles.includes(role))return res.status(400).json({error:{code:'INVITATION_INVALID',message:'Valid email and staff role are required.',requestId:req.requestId}});if(campusId){const {data}=await supabase.from('campuses').select('id').eq('id',campusId).eq('congregation_id',req.congregationId).maybeSingle();if(!data)return res.status(400).json({error:{code:'CAMPUS_INVALID',message:'Campus is not part of this organization.',requestId:req.requestId}});}const token=randomBytes(32).toString('base64url');const {data,error}=await supabase.from('staff_invitations').insert({congregation_id:req.congregationId,email,role,campus_id:campusId,token_hash:hash(token),invited_by:req.user.id}).select('id,expires_at').single();if(error)throw error;const frontend=(process.env.FRONTEND_URL||'').replace(/\/$/,'');const {error:emailError}=await supabase.auth.admin.inviteUserByEmail(email,{redirectTo:`${frontend}/auth/callback?next=${encodeURIComponent(`/staff-invite?token=${token}`)}`});if(emailError)throw emailError;await supabase.from('audit_events').insert({congregation_id:req.congregationId,actor_user_id:req.user.id,action:'staff.invited',resource_type:'staff_invitation',resource_id:data.id,request_id:req.requestId,metadata:{role,campusId}});res.status(201).json({data});}catch(error){next(error);}});

router.patch('/:congregationId/memberships/:membershipId', authenticateUser, requireCapability('staff.manage'), async(req,res,next)=>{try{const updates={};if(req.body.role!==undefined){if(!roles.includes(req.body.role))return res.status(400).json({error:{code:'ROLE_INVALID',message:'Staff role is invalid.',requestId:req.requestId}});updates.role=req.body.role;}if(req.body.campusId!==undefined)updates.campus_id=req.body.campusId||null;if(req.body.active!==undefined)updates.active=Boolean(req.body.active);const {data,error}=await supabase.from('organization_memberships').update(updates).eq('id',req.params.membershipId).eq('congregation_id',req.congregationId).select().maybeSingle();if(error)throw error;if(!data)return res.status(404).json({error:{code:'NOT_FOUND',message:'Staff membership not found.',requestId:req.requestId}});await supabase.from('audit_events').insert({congregation_id:req.congregationId,actor_user_id:req.user.id,action:'staff.membership_changed',resource_type:'organization_membership',resource_id:String(data.id),request_id:req.requestId,metadata:{fields:Object.keys(updates)}});res.json({data});}catch(error){next(error);}});

router.put('/:congregationId/memberships/:membershipId/overrides/:capability', authenticateUser, requireCapability('staff.manage'), async(req,res,next)=>{try{const capability=req.params.capability;if(!capabilities.includes(capability))return res.status(400).json({error:{code:'CAPABILITY_INVALID',message:'Capability is invalid.',requestId:req.requestId}});const {data:membership}=await supabase.from('organization_memberships').select('id').eq('id',req.params.membershipId).eq('congregation_id',req.congregationId).maybeSingle();if(!membership)return res.status(404).json({error:{code:'NOT_FOUND',message:'Staff membership not found.',requestId:req.requestId}});const {data,error}=await supabase.from('capability_overrides').upsert({membership_id:membership.id,capability,allowed:Boolean(req.body.allowed)},{onConflict:'membership_id,capability'}).select().single();if(error)throw error;await supabase.from('audit_events').insert({congregation_id:req.congregationId,actor_user_id:req.user.id,action:'staff.capability_changed',resource_type:'capability_override',resource_id:String(data.id),request_id:req.requestId,metadata:{capability,allowed:data.allowed}});res.json({data});}catch(error){next(error);}});

router.post('/invitations/accept', authenticateUser, async(req,res,next)=>{try{const token=String(req.body?.token||'');const {data:invitation,error}=await supabase.from('staff_invitations').select('*').eq('token_hash',hash(token)).is('accepted_at',null).gt('expires_at',new Date().toISOString()).maybeSingle();if(error)throw error;if(!invitation||invitation.email!==req.user.email?.toLowerCase())return res.status(403).json({error:{code:'INVITATION_INVALID',message:'Invitation is invalid or expired.',requestId:req.requestId}});const {data:membership,error:membershipError}=await supabase.from('organization_memberships').upsert({congregation_id:invitation.congregation_id,user_id:req.user.id,role:invitation.role,campus_id:invitation.campus_id,active:true},{onConflict:'congregation_id,user_id,campus_id'}).select().single();if(membershipError)throw membershipError;await supabase.from('staff_invitations').update({accepted_at:new Date().toISOString()}).eq('id',invitation.id);await supabase.from('audit_events').insert({congregation_id:invitation.congregation_id,actor_user_id:req.user.id,action:'staff.invitation_accepted',resource_type:'organization_membership',resource_id:String(membership.id),request_id:req.requestId});res.json({data:membership});}catch(error){next(error);}});
module.exports=router;
