-- LOCAL TEST TEMPLATE ONLY. Do not include this file in production migration runs.
-- A fresh disposable database needs the legacy dependency used by the additive
-- P0 migration. Hosted environments already have this table.
create table if not exists public.congregations (
  congregation_id bigint generated by default as identity primary key,
  name text not null,
  leader_user_id uuid references auth.users(id),
  invite_token text,
  stripe_account_id text,
  stripe_charges_enabled boolean not null default false,
  stripe_details_submitted boolean not null default false,
  created_at timestamptz not null default now()
);
