const supabase = require('../config/supabase');
const openai = require('../config/openai'); // Using your existing config
require('dotenv').config();

const EVAL_CONFIG = [
    { 
        table: 'daily_devotionals', 
        promptKey: 'daily_devotional_generator', 
        contentField: 'content',
        idField: 'devotional_id' // Corrected ID
    },
    { 
        table: 'daily_prayers', 
        promptKey: 'daily_prayer_generator', 
        contentField: 'generated_prayer',
        idField: 'prayer_id' 
    },
    { 
        table: 'scriptural_outlooks', 
        promptKey: 'news_generator', 
        contentField: 'ai_outlook',
        idField: 'id' // Corrected ID
    },
    { 
        table: 'advice_guidance', 
        promptKey: 'advice_guidance_generator', 
        contentField: 'advice_points',
        idField: 'advice_id' // Corrected ID
    }
];

async function evaluate() {
    console.log('🚀 Starting Batch Prompt Evaluation...');

    for (const config of EVAL_CONFIG) {
        console.log(`\n--- Batch Evaluating ${config.table} ---`);

        // 1. Fetch System Prompt
        const { data: promptData, error: promptError } = await supabase
            .from('system_prompts')
            .select('content')
            .eq('key', config.promptKey)
            .single();

        if (promptError || !promptData) {
            console.error(`[Error] Could not find prompt: ${config.promptKey}`, promptError);
            continue;
        }

        // 2. Fetch 5 latest samples using the correct ID fields
        const { data: samples, error: sampleError } = await supabase
            .from(config.table)
            .select(`*`)
            .order('created_at', { ascending: false })
            .limit(5);

        if (sampleError || !samples || samples.length === 0) {
            console.error(`[Error] No samples found for ${config.table}`, sampleError);
            continue;
        }

        // Prepare the batch of content for the AI to review
        
        const batchContent = samples.map((s, i) =>{
            // if contentfield is object, convert to string
            if(s[config.contentField] && typeof s[config.contentField] === 'object'){
                s[config.contentField] = JSON.stringify(s[config.contentField], null, 2);
            }
         return `SAMPLE ${i+1} (ID: ${s[config.idField]}):\n${s[config.contentField]}`;
        }).join('\n\n---\n\n');
        const sampleIds = samples.map(s => s[config.idField]).join(', ');

        // 3. The "Batch Judge" Prompt
        const judgeSystemPrompt = `
            You are an expert AI Prompt Engineer and Theological Critic. 
            Evaluate the following batch of 5 content pieces generated by the SAME system prompt.
            
            SOURCE TABLE: ${config.table}
            SYSTEM PROMPT:
            """
            ${promptData.content}
            """

            GENERATED BATCH:
            """
            ${batchContent}
            """

            TASK:
            1. Grade the overall QUALITY of the generated samples (A-F). Consider consistency and theological depth.
            2. Grade the SYSTEM PROMPT (A-F). Does it successfully guide the AI across multiple attempts?
            3. Provide a combined CRITIQUE. 
            4. Suggest a BETTER PROMPT to improve quality and consistency.

            Return ONLY a valid JSON object:
            {
                "quality_grade": "...",
                "quality_critique": "...",
                "prompt_grade": "...",
                "prompt_critique": "...",
                "suggested_prompt_update": "..."
            }
        `;

        try {
            const response = await openai.chat.completions.create({
                model: "gpt-4o",
                messages: [{ role: "system", content: judgeSystemPrompt }],
                response_format: { type: "json_object" }
            });

            const result = JSON.parse(response.choices[0].message.content);

            // 4. Save Batch Evaluation
            const { error: saveError } = await supabase
                .from('prompt_evaluations')
                .insert({
                    prompt_key: config.promptKey,
                    source_table: config.table,
                    source_id: samples[0][config.idField], // Link to the first ID in the batch as reference
                    generated_content: `Batch of 5 IDs: ${sampleIds}`,
                    original_prompt: promptData.content,
                    ...result
                });

            if (saveError) {
                console.error(`[Error] Failed to save evaluation for ${config.table}:`, saveError);
            } else {
                console.log(`✅ Batch Evaluation Saved for ${config.table} (Prompt Grade: ${result.prompt_grade})`);
            }
        } catch (err) {
            console.error(`[Error] AI evaluation failed for ${config.table}:`, err.message);
        }
    }
    console.log('\n✨ All batches processed.');
}

evaluate();