-- Make weekly formation planning auditable and preserve overwritten future content.

alter table public.devotional_themes
  add column if not exists curriculum_version text,
  add column if not exists starts_on date,
  add column if not exists ends_on date,
  add column if not exists season text,
  add column if not exists formation_goal text,
  add column if not exists pastoral_need text,
  add column if not exists theological_claim text,
  add column if not exists guardrails jsonb,
  add column if not exists week_plan jsonb;

create table if not exists public.devotional_week_plans (
  id bigint generated by default as identity primary key,
  start_date date not null unique,
  end_date date not null,
  theme_week_number integer references public.devotional_themes(week_number),
  theme_title text not null,
  formation_goal text not null,
  plan jsonb not null,
  prompt_version text not null default 'weekly-formation-v2',
  model text,
  status text not null default 'generated' check (status in ('generated', 'published', 'replaced', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.general_devotional_revisions (
  id bigint generated by default as identity primary key,
  devotional_id bigint,
  devotional_date date not null,
  previous_row jsonb not null,
  replacement_reason text not null default 'future curriculum regeneration',
  archived_at timestamptz not null default now()
);

create or replace function public.archive_general_devotional_revision()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if to_jsonb(old) is distinct from to_jsonb(new) then
    insert into public.general_devotional_revisions (devotional_id, devotional_date, previous_row)
    values (old.id, old.date, to_jsonb(old));
  end if;
  return new;
end;
$$;

drop trigger if exists archive_general_devotional_before_update on public.general_devotionals;
create trigger archive_general_devotional_before_update
before update on public.general_devotionals
for each row execute function public.archive_general_devotional_revision();

alter table public.devotional_week_plans enable row level security;
alter table public.general_devotional_revisions enable row level security;

drop policy if exists "Service role manages devotional week plans" on public.devotional_week_plans;
create policy "Service role manages devotional week plans"
on public.devotional_week_plans for all to service_role using (true) with check (true);

drop policy if exists "Service role manages devotional revisions" on public.general_devotional_revisions;
create policy "Service role manages devotional revisions"
on public.general_devotional_revisions for all to service_role using (true) with check (true);

grant all on table public.devotional_week_plans to service_role;
grant all on table public.general_devotional_revisions to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.system_prompts (key, content, description, updated_at)
values (
  'devotional_syllabus_generator',
  $prompt$
# SANCTUARY ANNUAL FORMATION CURRICULUM PLANNER

Design a dated 52-week Christian formation curriculum, not a list of religious topics. Every week must pursue one clear formation goal through seven non-interchangeable daily steps. Removing any day should leave a visible gap in the week's progression. Do not use seven synonyms or seven supporting verses to restate one thesis.

## Requirements
- Use the supplied calendar year and place Advent, Christmas, Lent, Holy Week, Easter, and Pentecost on their actual dates when appropriate to the ecumenical calendar.
- Balance Old and New Testaments, biblical genres, core doctrines, Christian practices, relationships, vocation, suffering, justice and mercy, mission, celebration, lament, and life in the church.
- Give every week a specific formation goal, pastoral need, theological claim, anchor passage, interpretive guardrails, and seven distinct day briefs.
- Flag denominationally disputed applications for editorial review rather than presenting one tradition as universal.
- Keep adjacent weeks distinct in outcome, emotional register, primary texts, and practices.
- For each day provide a movement, daily angle, human situation, central claim, contextual Scripture reference, observable same-day practice, title direction, and share mode.
- Title directions must reveal the day's distinctive value without the weekly label. Avoid generic openings such as “Embracing,” “Walking in,” “The Heart of,” “The Path of,” “Living in,” and “The Gift of.”

Return valid JSON with `curriculum_version`, 52 `weeks`, and a `coverage_audit`. Each week must contain `week`, `starts_on`, `ends_on`, `season`, `theme`, `formation_goal`, `pastoral_need`, `theological_claim`, `anchor_passage`, `guardrails`, and exactly seven `days`.
$prompt$,
  'Creates a dated, versioned annual formation map with seven-day weekly arcs.',
  now()
)
on conflict (key) do update set
  content = excluded.content,
  description = excluded.description,
  updated_at = excluded.updated_at;

update public.system_prompts
set content = replace(content,
  '5. Practice: end with one small, specific action or reflection for today. When natural, point toward shared prayer, a trusted person, a small group, or a local church rather than leaving faith isolated on a screen.',
  '5. Practice: end with one observable action that can be completed today. Include what to do and its time, setting, or recipient. Reflection alone does not count unless it produces a written, spoken, scheduled, given, asked, heard, or served response. When natural, point toward shared prayer, a trusted person, a small group, or a local church.'
), updated_at = now()
where key = 'daily_devotional_generator';

update public.system_prompts
set content = replace(content,
  '3. Use personal context as a possibility, not a diagnosis. Never infer trauma, sin, illness, risk, or life circumstances that were not supplied.',
  '3. Select at most one relevant application context for today. Do not enumerate unrelated profile concerns. Use personal context as a possibility, not a diagnosis, and never infer trauma, sin, illness, risk, or circumstances that were not supplied.'
), updated_at = now()
where key = 'daily_devotional_personalization_wrapper';

update public.system_prompts
set content = $prompt$
# SANCTUARY WEEKLY DEVOTIONAL WRITER

Create seven devotionals only from a supplied, validated weekly formation plan. Preserve every day's assigned Scripture, central claim, human situation, pastoral movement, practice, and share mode. The days must progress toward one formation goal without restating the weekly theme.

For each day:
- Write 120-160 words in a wise, biblically grounded, compassionate pastoral voice.
- Explain what the passage contributes in its literary or historical context. Never attribute another passage's language or story to the selected text.
- Include one useful pastoral distinction or insight rather than generic motivation.
- End with the planned observable same-day practice, including its time, setting, or recipient.
- Use a unique 4-9 word title that makes sense without the weekly theme. Do not begin with “Embracing,” “Walking in,” “The Heart of,” “The Path of,” “Living in,” or “The Gift of.”
- Return a 1-2 sentence prayer and exactly three short-form slides: Notice, Ground, and Practice.

Before returning, compare all seven titles, central claims, situations, openings, and practices. Revise any two days that deliver the same benefit. Return valid JSON only using the existing `devotionals` output shape.
$prompt$, updated_at = now()
where key = 'general_devotional_generator';
