begin;

create type public.staff_role as enum ('lead_pastor', 'care', 'ministry', 'finance', 'check_in', 'content');
create type public.capability as enum (
  'people.read', 'people.write', 'care.read', 'care.confidential', 'care.write',
  'finance.read', 'finance.write', 'check_in.read', 'check_in.write', 'check_in.override',
  'events.read', 'events.write', 'volunteers.read', 'volunteers.write',
  'communications.read', 'communications.write', 'content.read', 'content.write',
  'staff.manage', 'audit.read', 'organization.export'
);

create table if not exists public.campuses (
  id bigint generated by default as identity primary key,
  congregation_id integer not null references public.congregations(congregation_id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (congregation_id, name)
);

create table if not exists public.organization_memberships (
  id bigint generated by default as identity primary key,
  congregation_id integer not null references public.congregations(congregation_id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.staff_role not null,
  campus_id bigint references public.campuses(id) on delete cascade,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (congregation_id, user_id, campus_id)
);

create table if not exists public.capability_overrides (
  id bigint generated by default as identity primary key,
  membership_id bigint not null references public.organization_memberships(id) on delete cascade,
  capability public.capability not null,
  allowed boolean not null,
  created_at timestamptz not null default now(),
  unique (membership_id, capability)
);

-- Additive compatibility backfill. Existing leader_user_id authorization remains
-- unchanged until a separately approved RLS enforcement migration.
insert into public.organization_memberships(congregation_id, user_id, role)
select congregation_id, leader_user_id, 'lead_pastor'::public.staff_role
from public.congregations
where leader_user_id is not null
on conflict do nothing;

create table if not exists public.role_capabilities (
  role public.staff_role not null,
  capability public.capability not null,
  primary key (role, capability)
);

insert into public.role_capabilities(role, capability)
select 'lead_pastor'::public.staff_role, unnest(enum_range(null::public.capability))
on conflict do nothing;

insert into public.role_capabilities(role, capability)
select role::public.staff_role, capability::public.capability from (values
  ('care', 'people.read'), ('care', 'care.read'), ('care', 'care.confidential'), ('care', 'care.write'),
  ('ministry', 'people.read'), ('ministry', 'events.read'), ('ministry', 'events.write'), ('ministry', 'volunteers.read'), ('ministry', 'volunteers.write'), ('ministry', 'communications.read'), ('ministry', 'communications.write'),
  ('finance', 'people.read'), ('finance', 'finance.read'), ('finance', 'finance.write'),
  ('check_in', 'people.read'), ('check_in', 'check_in.read'), ('check_in', 'check_in.write'),
  ('content', 'content.read'), ('content', 'content.write'), ('content', 'communications.read'), ('content', 'communications.write')
) as defaults(role, capability)
on conflict do nothing;

create or replace function public.has_congregation_capability(
  requested_congregation_id integer,
  requested_capability text,
  requested_user_id uuid default auth.uid(),
  requested_campus_id bigint default null
) returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1
    from public.organization_memberships membership
    left join public.role_capabilities defaults
      on defaults.role = membership.role and defaults.capability = requested_capability::public.capability
    left join public.capability_overrides override
      on override.membership_id = membership.id and override.capability = requested_capability::public.capability
    where membership.congregation_id = requested_congregation_id
      and membership.user_id = requested_user_id
      and membership.active
      and (membership.campus_id is null or requested_campus_id is null or membership.campus_id = requested_campus_id)
      and coalesce(override.allowed, defaults.capability is not null)
  );
$$;
revoke all on function public.has_congregation_capability(integer,text,uuid,bigint) from public;
grant execute on function public.has_congregation_capability(integer,text,uuid,bigint) to authenticated, service_role;

create table if not exists public.audit_events (
  id uuid primary key default gen_random_uuid(),
  congregation_id integer references public.congregations(congregation_id),
  actor_user_id uuid references auth.users(id),
  action text not null,
  resource_type text not null,
  resource_id text,
  request_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create or replace function public.prevent_audit_mutation() returns trigger language plpgsql as $$
begin raise exception 'Audit events are immutable'; end;
$$;
drop trigger if exists audit_events_immutable on public.audit_events;
create trigger audit_events_immutable before update or delete on public.audit_events
for each row execute function public.prevent_audit_mutation();

create table if not exists public.guardian_relationships (
  id bigint generated by default as identity primary key,
  congregation_id integer not null references public.congregations(congregation_id) on delete cascade,
  guardian_profile_id uuid not null references public.church_crm_profiles(id) on delete cascade,
  child_profile_id uuid not null references public.church_crm_profiles(id) on delete cascade,
  relationship text not null,
  pickup_authorized boolean not null default true,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  unique (congregation_id, guardian_profile_id, child_profile_id)
);
create table if not exists public.medical_alerts (
  id bigint generated by default as identity primary key,
  congregation_id integer not null references public.congregations(congregation_id) on delete cascade,
  child_profile_id uuid not null references public.church_crm_profiles(id) on delete cascade,
  alert_type text not null check (alert_type in ('allergy','medical','accessibility','other')),
  description text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.kiosk_sessions (
  id uuid primary key default gen_random_uuid(),
  congregation_id integer not null references public.congregations(congregation_id) on delete cascade,
  event_id uuid references public.events(id) on delete cascade,
  opened_by uuid not null references auth.users(id),
  locked_at timestamptz,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create table if not exists public.pickup_credentials (
  id uuid primary key default gen_random_uuid(),
  congregation_id integer not null references public.congregations(congregation_id) on delete cascade,
  check_in_id uuid not null references public.check_ins(id) on delete cascade,
  credential_hash text not null,
  expires_at timestamptz not null,
  verified_at timestamptz,
  verified_by uuid references auth.users(id),
  override_reason text,
  unique (check_in_id)
);

-- Only brand-new P0 tables are protected here. This migration deliberately does
-- not enable or modify RLS on any legacy production table.
alter table public.organization_memberships enable row level security;
alter table public.capability_overrides enable row level security;
alter table public.campuses enable row level security;
alter table public.audit_events enable row level security;
alter table public.guardian_relationships enable row level security;
alter table public.medical_alerts enable row level security;
alter table public.kiosk_sessions enable row level security;
alter table public.pickup_credentials enable row level security;

create policy memberships_visible_to_staff on public.organization_memberships for select to authenticated
using (user_id = auth.uid() or public.has_congregation_capability(congregation_id, 'staff.manage', auth.uid(), null::bigint));
create policy campuses_visible_to_staff on public.campuses for select to authenticated
using (exists (select 1 from public.organization_memberships m where m.congregation_id = campuses.congregation_id and m.user_id = auth.uid() and m.active));
create policy audit_visible_to_authorized_staff on public.audit_events for select to authenticated
using (public.has_congregation_capability(congregation_id, 'audit.read', auth.uid(), null::bigint));
create policy guardians_visible_to_checkin on public.guardian_relationships for select to authenticated
using (public.has_congregation_capability(congregation_id, 'check_in.read', auth.uid(), null::bigint));
create policy medical_visible_to_checkin on public.medical_alerts for select to authenticated
using (public.has_congregation_capability(congregation_id, 'check_in.read', auth.uid(), null::bigint));
create policy kiosk_visible_to_checkin on public.kiosk_sessions for select to authenticated
using (public.has_congregation_capability(congregation_id, 'check_in.read', auth.uid(), null::bigint));
create policy pickup_visible_to_checkin on public.pickup_credentials for select to authenticated
using (public.has_congregation_capability(congregation_id, 'check_in.read', auth.uid(), null::bigint));

commit;
