SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
CREATE EXTENSION IF NOT EXISTS "pgsodium";
COMMENT ON SCHEMA "public" IS 'standard public schema';
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
CREATE TYPE "public"."church_role" AS ENUM (
    'Dont Attend',
    'Layperson',
    'Hold Church Office',
    'Committee Leader',
    'Minister',
    'Pastor'
);
ALTER TYPE "public"."church_role" OWNER TO "postgres";
CREATE TYPE "public"."content_type" AS ENUM (
    'devotional',
    'prayer',
    'advice',
    'news'
);
ALTER TYPE "public"."content_type" OWNER TO "postgres";
CREATE OR REPLACE FUNCTION "public"."handle_new_user_whitelist"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  if exists (select 1 from public.whitelist where email = new.email) then
    -- Update profile tier to pro immediately
    update public.user_profiles
    set tier = 'pro'
    where user_id = new.id;
  end if;
  return new;
end;
$$;
ALTER FUNCTION "public"."handle_new_user_whitelist"() OWNER TO "postgres";
CREATE OR REPLACE FUNCTION "public"."set_user_id"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$BEGIN
  -- If auth.uid() is available, use it
  IF auth.uid() IS NOT NULL THEN
    NEW.user_id := auth.uid();
  -- Otherwise, keep the user_id that was provided in the query
  -- This effectively doesn't modify NEW.user_id
  END IF;

  RETURN NEW;
END;$$;
ALTER FUNCTION "public"."set_user_id"() OWNER TO "postgres";
SET default_tablespace = '';
SET default_table_access_method = "heap";
CREATE TABLE IF NOT EXISTS "public"."admin_emails" (
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
ALTER TABLE "public"."admin_emails" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."advice_guidance" (
    "advice_id" integer NOT NULL,
    "situation" "text",
    "advice_points" "jsonb",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid",
    "status" "text"
);
ALTER TABLE "public"."advice_guidance" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."advice_guidance_advice_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."advice_guidance_advice_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."advice_guidance_advice_id_seq" OWNED BY "public"."advice_guidance"."advice_id";
CREATE TABLE IF NOT EXISTS "public"."app_options" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "options" "jsonb",
    "updated_at" timestamp with time zone
);
ALTER TABLE "public"."app_options" OWNER TO "postgres";
ALTER TABLE "public"."app_options" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."app_options_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."bible_reading_journeys" (
    "journey_id" integer NOT NULL,
    "start_date" "date",
    "end_date" "date",
    "plan_name" character varying(255),
    "current_book" character varying(100),
    "current_chapter" integer,
    "last_read_date" "date",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid"
);
ALTER TABLE "public"."bible_reading_journeys" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."bible_reading_journeys_journey_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."bible_reading_journeys_journey_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."bible_reading_journeys_journey_id_seq" OWNED BY "public"."bible_reading_journeys"."journey_id";
CREATE TABLE IF NOT EXISTS "public"."bible_studies" (
    "study_id" integer NOT NULL,
    "title" character varying(255),
    "subtitle" "text",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "illustration" "text",
    "study_method" "text",
    "status" "text",
    "congregation_id" integer,
    "is_published" boolean DEFAULT false,
    "illustration_prompt" "text",
    "illustration_image_url" "text",
    "thumbnail_url" "text"
);
ALTER TABLE "public"."bible_studies" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."bible_studies_study_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."bible_studies_study_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."bible_studies_study_id_seq" OWNED BY "public"."bible_studies"."study_id";
ALTER TABLE "public"."bible_studies" ALTER COLUMN "study_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bible_studies_study_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."bible_study_lessons" (
    "lesson_id" integer NOT NULL,
    "study_id" integer NOT NULL,
    "lesson_number" integer NOT NULL,
    "title" character varying(255),
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "study_outline" "jsonb",
    "commentary" "text",
    "reflection_questions" "jsonb",
    "scripture" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "key_verse" "text",
    "lesson_aims" "jsonb",
    "introduction" "jsonb",
    "discussion_starters" "jsonb",
    "application_sidebar" "jsonb",
    "conclusion" "jsonb"
);
ALTER TABLE "public"."bible_study_lessons" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."bible_study_lessons_lesson_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."bible_study_lessons_lesson_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."bible_study_lessons_lesson_id_seq" OWNED BY "public"."bible_study_lessons"."lesson_id";
ALTER TABLE "public"."bible_study_lessons" ALTER COLUMN "lesson_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bible_study_lessons_lesson_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE "public"."bible_study_lessons" ALTER COLUMN "study_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bible_study_lessons_study_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "name" "text",
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "image_url" "text",
    "scriptural_breakdown" "text",
    "slug" "text"
);
ALTER TABLE "public"."categories" OWNER TO "postgres";
COMMENT ON TABLE "public"."categories" IS 'e.g. Politics, International, Celebrities';
CREATE TABLE IF NOT EXISTS "public"."check_ins" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "congregation_id" bigint,
    "event_id" "uuid",
    "profile_id" "uuid",
    "checked_in_by" "uuid",
    "secure_code" "text" NOT NULL,
    "status" "text" DEFAULT 'active'::"text",
    "checked_in_at" timestamp with time zone DEFAULT "now"(),
    "checked_out_at" timestamp with time zone,
    CONSTRAINT "check_ins_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'checked_out'::"text"])))
);
ALTER TABLE "public"."check_ins" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."church_crm_profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "congregation_id" bigint,
    "user_id" "uuid",
    "first_name" "text" NOT NULL,
    "last_name" "text",
    "email" "text",
    "phone" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "household_id" "uuid",
    "household_role" "text" DEFAULT 'adult'::"text",
    "medical_notes" "text",
    CONSTRAINT "church_crm_profiles_household_role_check" CHECK (("household_role" = ANY (ARRAY['primary'::"text", 'adult'::"text", 'child'::"text", 'dependent'::"text"])))
);
ALTER TABLE "public"."church_crm_profiles" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."community_prayer_interactions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "prayer_id" "uuid",
    "praying_user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."community_prayer_interactions" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."community_prayers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "original_content" "text" NOT NULL,
    "anonymized_content" "text",
    "status" "text" DEFAULT 'pending'::"text",
    "prayer_count" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."community_prayers" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."congregation_members" (
    "member_id" integer NOT NULL,
    "congregation_id" integer NOT NULL,
    "join_date" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid",
    "last_active_date" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "activity_score" integer DEFAULT 0
);
ALTER TABLE "public"."congregation_members" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."congregation_members_member_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."congregation_members_member_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."congregation_members_member_id_seq" OWNED BY "public"."congregation_members"."member_id";
CREATE TABLE IF NOT EXISTS "public"."congregations" (
    "congregation_id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "leader_user_id" "uuid" NOT NULL,
    "description" "text",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "invite_token" "uuid" DEFAULT "gen_random_uuid"(),
    "youtube_channel_id" "text",
    "stripe_account_id" "text",
    "stripe_charges_enabled" boolean DEFAULT false,
    "stripe_details_submitted" boolean DEFAULT false
);
ALTER TABLE "public"."congregations" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."congregations_congregation_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."congregations_congregation_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."congregations_congregation_id_seq" OWNED BY "public"."congregations"."congregation_id";
CREATE TABLE IF NOT EXISTS "public"."contact" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "email" "text",
    "message" "text"
);
ALTER TABLE "public"."contact" OWNER TO "postgres";
ALTER TABLE "public"."contact" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contact_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."content_feedback" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "content_id" "text" NOT NULL,
    "content_type" "text" NOT NULL,
    "rating" integer,
    "what_worked" "text",
    "what_didnt_work" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "content_feedback_rating_check" CHECK ((("rating" >= 1) AND ("rating" <= 5)))
);
ALTER TABLE "public"."content_feedback" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."counseling_sessions" (
    "session_id" integer NOT NULL,
    "counselor_user_id" integer NOT NULL,
    "client_name" character varying(255),
    "session_date" "date",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "public"."counseling_sessions" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."counseling_sessions_session_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."counseling_sessions_session_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."counseling_sessions_session_id_seq" OWNED BY "public"."counseling_sessions"."session_id";
CREATE TABLE IF NOT EXISTS "public"."curated_tracks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "video_id" "text" NOT NULL,
    "title" "text" NOT NULL,
    "artist" "text",
    "thumbnail_url" "text",
    "activities" "text"[] DEFAULT '{}'::"text"[],
    "focus_areas" "text"[] DEFAULT '{}'::"text"[],
    "improvement_areas" "text"[] DEFAULT '{}'::"text"[],
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."curated_tracks" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."daily_devotionals" (
    "devotional_id" integer NOT NULL,
    "content" "text",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid",
    "scripture" "text",
    "status" "text",
    "title" "text",
    "song_video_id" "text",
    "song_url" "text",
    "song_title" "text",
    "song_channel" "text",
    "song_thumbnail" "text",
    "short_form" "jsonb",
    CONSTRAINT "daily_devotionals_short_form_shape_check" CHECK ((("short_form" IS NULL) OR
CASE
    WHEN (("jsonb_typeof"("short_form") = 'object'::"text") AND (("short_form" ->> 'format'::"text") = 'instagram_story_3_slide'::"text") AND ("jsonb_typeof"(("short_form" -> 'slides'::"text")) = 'array'::"text")) THEN ("jsonb_array_length"(("short_form" -> 'slides'::"text")) = 3)
    ELSE false
END))
);
ALTER TABLE "public"."daily_devotionals" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."daily_devotionals_devotional_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."daily_devotionals_devotional_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."daily_devotionals_devotional_id_seq" OWNED BY "public"."daily_devotionals"."devotional_id";
CREATE TABLE IF NOT EXISTS "public"."daily_news_synopses" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "synopsis" "text",
    "scripture" "text",
    "prayer" "text"
);
ALTER TABLE "public"."daily_news_synopses" OWNER TO "postgres";
ALTER TABLE "public"."daily_news_synopses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."daily_news_synopses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."daily_prayers" (
    "prayer_id" integer NOT NULL,
    "date" "date" NOT NULL,
    "generated_prayer" "text",
    "went_through_guided_prayer" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid",
    "status" "text"
);
ALTER TABLE "public"."daily_prayers" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."daily_prayers_prayer_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."daily_prayers_prayer_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."daily_prayers_prayer_id_seq" OWNED BY "public"."daily_prayers"."prayer_id";
CREATE TABLE IF NOT EXISTS "public"."devotional_themes" (
    "week_number" integer NOT NULL,
    "theme_title" "text" NOT NULL,
    "scripture_focus" "text",
    "is_used" boolean DEFAULT false
);
ALTER TABLE "public"."devotional_themes" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."event_volunteers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "event_id" "uuid",
    "role_id" "uuid",
    "user_id" "uuid",
    "status" "text" DEFAULT 'pending'::"text",
    "notified_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "event_volunteers_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'accepted'::"text", 'declined'::"text"])))
);
ALTER TABLE "public"."event_volunteers" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."events" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "congregation_id" bigint,
    "title" "text" NOT NULL,
    "description" "text",
    "event_date" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone,
    "location" "text",
    "event_type" "text" DEFAULT 'service'::"text",
    "is_public" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "organizer_id" "uuid",
    "manage_token" "uuid" DEFAULT "gen_random_uuid"(),
    "status" "text" DEFAULT 'draft'::"text",
    "cover_image_url" "text",
    CONSTRAINT "events_status_check" CHECK (("status" = ANY (ARRAY['draft'::"text", 'published'::"text", 'completed'::"text"])))
);
ALTER TABLE "public"."events" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."favorites" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "item_id" "text" NOT NULL,
    "item_type" "public"."content_type" NOT NULL,
    "title" "text",
    "preview" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."favorites" OWNER TO "postgres";
ALTER TABLE "public"."favorites" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."favorites_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."friends" (
    "friendship_id" integer NOT NULL,
    "friend_user_id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid"
);
ALTER TABLE "public"."friends" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."friends_friendship_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."friends_friendship_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."friends_friendship_id_seq" OWNED BY "public"."friends"."friendship_id";
CREATE TABLE IF NOT EXISTS "public"."general_devotionals" (
    "id" bigint NOT NULL,
    "date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "scripture_reference" "text" NOT NULL,
    "scripture_text" "text" NOT NULL,
    "content" "text" NOT NULL,
    "prayer" "text" NOT NULL,
    "topics" "text"[],
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "short_form" "jsonb",
    CONSTRAINT "general_devotionals_short_form_shape_check" CHECK ((("short_form" IS NULL) OR
CASE
    WHEN (("jsonb_typeof"("short_form") = 'object'::"text") AND (("short_form" ->> 'format'::"text") = 'instagram_story_3_slide'::"text") AND ("jsonb_typeof"(("short_form" -> 'slides'::"text")) = 'array'::"text")) THEN ("jsonb_array_length"(("short_form" -> 'slides'::"text")) = 3)
    ELSE false
END))
);
ALTER TABLE "public"."general_devotionals" OWNER TO "postgres";
ALTER TABLE "public"."general_devotionals" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."general_devotionals_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."households" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "congregation_id" bigint,
    "name" "text" NOT NULL,
    "primary_phone" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."households" OWNER TO "postgres";
ALTER TABLE "public"."categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."news_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."topics" (
    "id" bigint NOT NULL,
    "name" "text",
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "image_url" "text",
    "scriptural_breakdown" "text",
    "slug" "text"
);
ALTER TABLE "public"."topics" OWNER TO "postgres";
ALTER TABLE "public"."topics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."news_topics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."outlook_categories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "outlook_id" bigint,
    "category_id" bigint
);
ALTER TABLE "public"."outlook_categories" OWNER TO "postgres";
ALTER TABLE "public"."outlook_categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."outlook_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."outlook_topics" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "outlook_id" bigint,
    "topic_id" bigint
);
ALTER TABLE "public"."outlook_topics" OWNER TO "postgres";
ALTER TABLE "public"."outlook_topics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."outlook_topics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."pastoral_messages" (
    "message_id" integer NOT NULL,
    "congregation_id" integer,
    "video_asset_id" "text",
    "thumbnail_url" "text",
    "title" "text",
    "message_type" "text" DEFAULT 'message'::"text",
    "is_published" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "video_playback_id" "text",
    "message_body" "text"
);
ALTER TABLE "public"."pastoral_messages" OWNER TO "postgres";
ALTER TABLE "public"."pastoral_messages" ALTER COLUMN "message_id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."pastoral_messages_message_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."pastoral_notes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "crm_profile_id" "uuid",
    "author_id" "uuid",
    "note_text" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."pastoral_notes" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."prayer_requests" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "congregation_id" bigint,
    "request_text" "text" NOT NULL,
    "visibility" "text" DEFAULT 'public_anonymous'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "prayer_requests_visibility_check" CHECK (("visibility" = ANY (ARRAY['public_anonymous'::"text", 'congregation'::"text", 'pastor'::"text"])))
);
ALTER TABLE "public"."prayer_requests" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."prompt_evaluations" (
    "id" bigint NOT NULL,
    "prompt_key" "text" NOT NULL,
    "source_table" "text" NOT NULL,
    "source_id" "text" NOT NULL,
    "generated_content" "text" NOT NULL,
    "original_prompt" "text" NOT NULL,
    "quality_grade" "text",
    "quality_critique" "text",
    "prompt_grade" "text",
    "prompt_critique" "text",
    "suggested_prompt_update" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."prompt_evaluations" OWNER TO "postgres";
ALTER TABLE "public"."prompt_evaluations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."prompt_evaluations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "subscription" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";
ALTER TABLE "public"."push_subscriptions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."push_subscriptions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."recommended_videos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "video_id" "text" NOT NULL,
    "video_url" "text" NOT NULL,
    "title" "text" NOT NULL,
    "thumbnail_url" "text",
    "transcript" "text",
    "focus_areas" "text"[] DEFAULT '{}'::"text"[],
    "improvement_areas" "text"[] DEFAULT '{}'::"text"[],
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "channel_id" "text",
    "channel_name" "text",
    "view_count" bigint
);
ALTER TABLE "public"."recommended_videos" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."role_members" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "role_id" "uuid",
    "user_id" "uuid",
    "status" "text" DEFAULT 'active'::"text",
    "joined_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "role_members_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'pending_approval'::"text"])))
);
ALTER TABLE "public"."role_members" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."scriptural_outlooks" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "article_url" "text",
    "article_title" "text",
    "article_body" "text",
    "ai_outlook" "jsonb",
    "article_thumbnail_url" "text",
    "publish_date" timestamp with time zone,
    "slug" "text",
    "news_impact_score" integer,
    "news_impact_summary" "text"
);
ALTER TABLE "public"."scriptural_outlooks" OWNER TO "postgres";
ALTER TABLE "public"."scriptural_outlooks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."scriptural_outlooks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."sermon_preferences" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "key" "text",
    "name" "text",
    "onboarding_title" "text",
    "onboarding_subtitle" "text",
    "onboarding_type" "text",
    "onboarding_choices" "jsonb"
);
ALTER TABLE "public"."sermon_preferences" OWNER TO "postgres";
ALTER TABLE "public"."sermon_preferences" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sermon_preferences_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."sermon_series" (
    "series_id" integer NOT NULL,
    "series_name" character varying(255),
    "description" "text",
    "start_date" "date",
    "end_date" "date",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid",
    "series_format" "text" DEFAULT 'standard'::"text" NOT NULL,
    CONSTRAINT "sermon_series_series_format_check" CHECK (("series_format" = ANY (ARRAY['standard'::"text", 'short_form'::"text"])))
);
ALTER TABLE "public"."sermon_series" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."sermon_series_series_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."sermon_series_series_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."sermon_series_series_id_seq" OWNED BY "public"."sermon_series"."series_id";
CREATE TABLE IF NOT EXISTS "public"."sermons" (
    "sermon_id" integer NOT NULL,
    "series_id" integer,
    "title" "text",
    "date_preached" "date",
    "sermon_outline" "jsonb",
    "sermon_body" "text",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "illustration" "text",
    "key_takeaways" "jsonb",
    "scripture" "text",
    "status" "text",
    "user_id" "uuid",
    "tags" "text"[] DEFAULT '{}'::"text"[],
    "content_format" "text" DEFAULT 'sermon'::"text" NOT NULL,
    "target_duration_min" integer,
    "actual_duration_min" integer,
    "distribution_channel" "text" DEFAULT 'pulpit'::"text" NOT NULL,
    "illustration_prompt" "text",
    "illustration_image_url" "text",
    "thumbnail_url" "text",
    CONSTRAINT "sermons_actual_duration_min_check" CHECK ((("actual_duration_min" IS NULL) OR (("actual_duration_min" >= 1) AND ("actual_duration_min" <= 240)))),
    CONSTRAINT "sermons_content_format_check" CHECK (("content_format" = ANY (ARRAY['sermon'::"text", 'sermonette'::"text", 'podcast_episode'::"text", 'youtube_video'::"text"]))),
    CONSTRAINT "sermons_distribution_channel_check" CHECK (("distribution_channel" = ANY (ARRAY['pulpit'::"text", 'podcast'::"text", 'youtube'::"text", 'multi'::"text"]))),
    CONSTRAINT "sermons_target_duration_min_check" CHECK ((("target_duration_min" IS NULL) OR (("target_duration_min" >= 1) AND ("target_duration_min" <= 240))))
);
ALTER TABLE "public"."sermons" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."sermons_sermon_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE "public"."sermons_sermon_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."sermons_sermon_id_seq" OWNED BY "public"."sermons"."sermon_id";
CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "id" "text" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "status" "text",
    "price_id" "text",
    "cancel_at_period_end" boolean,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "ended_at" timestamp with time zone,
    CONSTRAINT "subscriptions_status_check" CHECK (("status" = ANY (ARRAY['trialing'::"text", 'active'::"text", 'canceled'::"text", 'incomplete'::"text", 'past_due'::"text", 'unpaid'::"text", 'paused'::"text"])))
);
ALTER TABLE "public"."subscriptions" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."system_logs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "level" "text" NOT NULL,
    "source" "text" NOT NULL,
    "user_id" "uuid",
    "action" "text",
    "message" "text",
    "details" "jsonb",
    "duration_ms" integer,
    "is_local" boolean DEFAULT false
);
ALTER TABLE "public"."system_logs" OWNER TO "postgres";
COMMENT ON COLUMN "public"."system_logs"."is_local" IS 'whether or not the request is from local testing';
ALTER TABLE "public"."system_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."system_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."system_prompts" (
    "key" "text" NOT NULL,
    "content" "text" NOT NULL,
    "description" "text",
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."system_prompts" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."user_activities" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "activity_type" "text" NOT NULL,
    "activity_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "activity_id" "text",
    "description" "text"
);
ALTER TABLE "public"."user_activities" OWNER TO "postgres";
COMMENT ON COLUMN "public"."user_activities"."activity_id" IS 'id of the item interacted with';
ALTER TABLE "public"."user_activities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_activities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."user_followed_categories" (
    "user_id" "uuid" NOT NULL,
    "category_id" "text" NOT NULL
);
ALTER TABLE "public"."user_followed_categories" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."user_followed_topics" (
    "user_id" "uuid" NOT NULL,
    "topic_id" "text" NOT NULL
);
ALTER TABLE "public"."user_followed_topics" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."user_profiles" (
    "date_of_birth" "date",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid" NOT NULL,
    "sermon_preferences" "jsonb",
    "user_preferences" "jsonb",
    "tier" "text" DEFAULT ''::"text",
    "ai_tuning_notes" "text" DEFAULT ''::"text",
    "subscription_tier" "text" DEFAULT 'free'::"text" NOT NULL,
    "stripe_customer_id" "text",
    "stripe_subscription_id" "text",
    "advice_usage_count" integer DEFAULT 0,
    "advice_reset_date" timestamp with time zone DEFAULT "now"(),
    "community_requests_count" integer DEFAULT 0,
    "community_requests_reset_date" timestamp with time zone DEFAULT "now"(),
    "role" "text" DEFAULT 'authenticated'::"text",
    "expo_push_token" "text",
    "first_name" "text",
    "last_name" "text",
    "email" "text",
    "avatar_url" "text",
    CONSTRAINT "user_profiles_subscription_tier_check" CHECK (("subscription_tier" = ANY (ARRAY['free'::"text", 'pro'::"text", 'admin'::"text"])))
);
ALTER TABLE "public"."user_profiles" OWNER TO "postgres";
COMMENT ON COLUMN "public"."user_profiles"."advice_usage_count" IS 'Count of advice generations used in the current billing period';
CREATE TABLE IF NOT EXISTS "public"."users" (
    "email" character varying(255) NOT NULL,
    "password" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "user_id" "uuid",
    "role" "text" DEFAULT 'authenticated'::"text"
);
ALTER TABLE "public"."users" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."volunteer_roles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "congregation_id" bigint,
    "name" "text" NOT NULL,
    "color_code" "text" DEFAULT '#4f46e5'::"text",
    "join_policy" "text" DEFAULT 'invite_only'::"text",
    "description" "text",
    CONSTRAINT "volunteer_roles_join_policy_check" CHECK (("join_policy" = ANY (ARRAY['open'::"text", 'approval_required'::"text", 'invite_only'::"text"])))
);
ALTER TABLE "public"."volunteer_roles" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."whitelist" (
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);
ALTER TABLE "public"."whitelist" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."youtube_channels" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "channel_id" "text" NOT NULL,
    "channel_name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "handle" "text",
    "subscriber_count" bigint,
    "view_count" bigint,
    "video_count" bigint,
    "is_active" boolean DEFAULT true
);
ALTER TABLE "public"."youtube_channels" OWNER TO "postgres";
ALTER TABLE ONLY "public"."advice_guidance" ALTER COLUMN "advice_id" SET DEFAULT "nextval"('"public"."advice_guidance_advice_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."bible_reading_journeys" ALTER COLUMN "journey_id" SET DEFAULT "nextval"('"public"."bible_reading_journeys_journey_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."congregation_members" ALTER COLUMN "member_id" SET DEFAULT "nextval"('"public"."congregation_members_member_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."congregations" ALTER COLUMN "congregation_id" SET DEFAULT "nextval"('"public"."congregations_congregation_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."counseling_sessions" ALTER COLUMN "session_id" SET DEFAULT "nextval"('"public"."counseling_sessions_session_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."daily_devotionals" ALTER COLUMN "devotional_id" SET DEFAULT "nextval"('"public"."daily_devotionals_devotional_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."daily_prayers" ALTER COLUMN "prayer_id" SET DEFAULT "nextval"('"public"."daily_prayers_prayer_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."friends" ALTER COLUMN "friendship_id" SET DEFAULT "nextval"('"public"."friends_friendship_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."sermon_series" ALTER COLUMN "series_id" SET DEFAULT "nextval"('"public"."sermon_series_series_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."sermons" ALTER COLUMN "sermon_id" SET DEFAULT "nextval"('"public"."sermons_sermon_id_seq"'::"regclass");
ALTER TABLE ONLY "public"."admin_emails"
    ADD CONSTRAINT "admin_emails_pkey" PRIMARY KEY ("email");
ALTER TABLE ONLY "public"."advice_guidance"
    ADD CONSTRAINT "advice_guidance_pkey" PRIMARY KEY ("advice_id");
ALTER TABLE ONLY "public"."app_options"
    ADD CONSTRAINT "app_options_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."bible_reading_journeys"
    ADD CONSTRAINT "bible_reading_journeys_pkey" PRIMARY KEY ("journey_id");
ALTER TABLE ONLY "public"."bible_studies"
    ADD CONSTRAINT "bible_studies_pkey" PRIMARY KEY ("study_id");
ALTER TABLE ONLY "public"."bible_studies"
    ADD CONSTRAINT "bible_studies_study_id_key" UNIQUE ("study_id");
ALTER TABLE ONLY "public"."bible_study_lessons"
    ADD CONSTRAINT "bible_study_lessons_lesson_id_key" UNIQUE ("lesson_id");
ALTER TABLE ONLY "public"."bible_study_lessons"
    ADD CONSTRAINT "bible_study_lessons_pkey" PRIMARY KEY ("lesson_id");
ALTER TABLE ONLY "public"."bible_study_lessons"
    ADD CONSTRAINT "bible_study_lessons_study_id_lesson_number_key" UNIQUE ("study_id", "lesson_number");
ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_slug_key" UNIQUE ("slug");
ALTER TABLE ONLY "public"."check_ins"
    ADD CONSTRAINT "check_ins_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."church_crm_profiles"
    ADD CONSTRAINT "church_crm_profiles_congregation_id_user_id_key" UNIQUE ("congregation_id", "user_id");
ALTER TABLE ONLY "public"."church_crm_profiles"
    ADD CONSTRAINT "church_crm_profiles_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."community_prayer_interactions"
    ADD CONSTRAINT "community_prayer_interactions_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."community_prayers"
    ADD CONSTRAINT "community_prayers_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."congregation_members"
    ADD CONSTRAINT "congregation_members_pkey" PRIMARY KEY ("member_id");
ALTER TABLE ONLY "public"."congregations"
    ADD CONSTRAINT "congregations_invite_token_key" UNIQUE ("invite_token");
ALTER TABLE ONLY "public"."congregations"
    ADD CONSTRAINT "congregations_pkey" PRIMARY KEY ("congregation_id");
ALTER TABLE ONLY "public"."congregations"
    ADD CONSTRAINT "congregations_stripe_account_id_key" UNIQUE ("stripe_account_id");
ALTER TABLE ONLY "public"."contact"
    ADD CONSTRAINT "contact_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."content_feedback"
    ADD CONSTRAINT "content_feedback_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."counseling_sessions"
    ADD CONSTRAINT "counseling_sessions_pkey" PRIMARY KEY ("session_id");
ALTER TABLE ONLY "public"."curated_tracks"
    ADD CONSTRAINT "curated_tracks_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."curated_tracks"
    ADD CONSTRAINT "curated_tracks_video_id_key" UNIQUE ("video_id");
ALTER TABLE ONLY "public"."daily_devotionals"
    ADD CONSTRAINT "daily_devotionals_pkey" PRIMARY KEY ("devotional_id");
ALTER TABLE ONLY "public"."daily_news_synopses"
    ADD CONSTRAINT "daily_news_synopses_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."daily_prayers"
    ADD CONSTRAINT "daily_prayers_pkey" PRIMARY KEY ("prayer_id");
ALTER TABLE ONLY "public"."devotional_themes"
    ADD CONSTRAINT "devotional_themes_pkey" PRIMARY KEY ("week_number");
ALTER TABLE ONLY "public"."event_volunteers"
    ADD CONSTRAINT "event_volunteers_event_id_user_id_role_id_key" UNIQUE ("event_id", "user_id", "role_id");
ALTER TABLE ONLY "public"."event_volunteers"
    ADD CONSTRAINT "event_volunteers_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."favorites"
    ADD CONSTRAINT "favorites_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."favorites"
    ADD CONSTRAINT "favorites_user_id_item_id_item_type_key" UNIQUE ("user_id", "item_id", "item_type");
ALTER TABLE ONLY "public"."friends"
    ADD CONSTRAINT "friends_pkey" PRIMARY KEY ("friendship_id");
ALTER TABLE ONLY "public"."general_devotionals"
    ADD CONSTRAINT "general_devotionals_date_key" UNIQUE ("date");
ALTER TABLE ONLY "public"."general_devotionals"
    ADD CONSTRAINT "general_devotionals_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."households"
    ADD CONSTRAINT "households_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "news_categories_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."topics"
    ADD CONSTRAINT "news_topics_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."outlook_categories"
    ADD CONSTRAINT "outlook_categories_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."outlook_topics"
    ADD CONSTRAINT "outlook_topics_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."pastoral_messages"
    ADD CONSTRAINT "pastoral_messages_pkey" PRIMARY KEY ("message_id");
ALTER TABLE ONLY "public"."pastoral_notes"
    ADD CONSTRAINT "pastoral_notes_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."prayer_requests"
    ADD CONSTRAINT "prayer_requests_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."prompt_evaluations"
    ADD CONSTRAINT "prompt_evaluations_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_user_id_subscription_key" UNIQUE ("user_id", "subscription");
ALTER TABLE ONLY "public"."recommended_videos"
    ADD CONSTRAINT "recommended_videos_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."recommended_videos"
    ADD CONSTRAINT "recommended_videos_video_id_key" UNIQUE ("video_id");
ALTER TABLE ONLY "public"."role_members"
    ADD CONSTRAINT "role_members_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."role_members"
    ADD CONSTRAINT "role_members_role_id_user_id_key" UNIQUE ("role_id", "user_id");
ALTER TABLE ONLY "public"."scriptural_outlooks"
    ADD CONSTRAINT "scriptural_outlooks_article_url_key" UNIQUE ("article_url");
ALTER TABLE ONLY "public"."scriptural_outlooks"
    ADD CONSTRAINT "scriptural_outlooks_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."scriptural_outlooks"
    ADD CONSTRAINT "scriptural_outlooks_slug_key" UNIQUE ("slug");
ALTER TABLE ONLY "public"."sermon_preferences"
    ADD CONSTRAINT "sermon_preferences_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."sermon_series"
    ADD CONSTRAINT "sermon_series_pkey" PRIMARY KEY ("series_id");
ALTER TABLE ONLY "public"."sermons"
    ADD CONSTRAINT "sermons_pkey" PRIMARY KEY ("sermon_id");
ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."system_logs"
    ADD CONSTRAINT "system_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."system_prompts"
    ADD CONSTRAINT "system_prompts_pkey" PRIMARY KEY ("key");
ALTER TABLE ONLY "public"."topics"
    ADD CONSTRAINT "topics_slug_key" UNIQUE ("slug");
ALTER TABLE ONLY "public"."user_activities"
    ADD CONSTRAINT "user_activities_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."user_followed_categories"
    ADD CONSTRAINT "user_followed_categories_pkey" PRIMARY KEY ("user_id", "category_id");
ALTER TABLE ONLY "public"."user_followed_topics"
    ADD CONSTRAINT "user_followed_topics_pkey" PRIMARY KEY ("user_id", "topic_id");
ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("user_id");
ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");
ALTER TABLE ONLY "public"."volunteer_roles"
    ADD CONSTRAINT "volunteer_roles_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."whitelist"
    ADD CONSTRAINT "whitelist_pkey" PRIMARY KEY ("email");
ALTER TABLE ONLY "public"."youtube_channels"
    ADD CONSTRAINT "youtube_channels_channel_id_key" UNIQUE ("channel_id");
ALTER TABLE ONLY "public"."youtube_channels"
    ADD CONSTRAINT "youtube_channels_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_crm_congregation" ON "public"."church_crm_profiles" USING "btree" ("congregation_id");
CREATE INDEX "idx_event_volunteers_user" ON "public"."event_volunteers" USING "btree" ("user_id");
CREATE INDEX "idx_events_congregation_date" ON "public"."events" USING "btree" ("congregation_id", "event_date");
CREATE INDEX "idx_events_manage_token" ON "public"."events" USING "btree" ("manage_token");
CREATE INDEX "idx_households_phone" ON "public"."households" USING "btree" ("primary_phone");
CREATE INDEX "idx_prayers_congregation" ON "public"."prayer_requests" USING "btree" ("congregation_id");
CREATE INDEX "idx_profiles_household" ON "public"."church_crm_profiles" USING "btree" ("household_id");
CREATE INDEX "idx_recommended_videos_channel_id" ON "public"."recommended_videos" USING "btree" ("channel_id");
CREATE INDEX "idx_recommended_videos_view_count" ON "public"."recommended_videos" USING "btree" ("view_count" DESC NULLS LAST);
CREATE INDEX "idx_role_members_role" ON "public"."role_members" USING "btree" ("role_id");
CREATE INDEX "idx_role_members_user" ON "public"."role_members" USING "btree" ("user_id");
CREATE INDEX "idx_scriptural_outlooks_created_at" ON "public"."scriptural_outlooks" USING "btree" ("created_at" DESC);
CREATE INDEX "idx_scriptural_outlooks_news_impact_score" ON "public"."scriptural_outlooks" USING "btree" ("news_impact_score" DESC, "created_at" DESC);
CREATE INDEX "idx_sermon_series_user_series_format" ON "public"."sermon_series" USING "btree" ("user_id", "series_format");
CREATE INDEX "idx_sermons_user_content_format" ON "public"."sermons" USING "btree" ("user_id", "content_format");
CREATE INDEX "idx_sermons_user_distribution_channel" ON "public"."sermons" USING "btree" ("user_id", "distribution_channel");
CREATE INDEX "idx_tracks_active" ON "public"."curated_tracks" USING "btree" ("is_active");
CREATE INDEX "idx_tracks_activities" ON "public"."curated_tracks" USING "gin" ("activities");
CREATE INDEX "idx_tracks_focus" ON "public"."curated_tracks" USING "gin" ("focus_areas");
CREATE INDEX "idx_user_profiles_email_lower" ON "public"."user_profiles" USING "btree" ("lower"("email"));
CREATE INDEX "idx_youtube_channels_active_subs" ON "public"."youtube_channels" USING "btree" ("is_active", "subscriber_count" DESC NULLS LAST, "view_count" DESC NULLS LAST);
CREATE INDEX "idx_youtube_channels_handle_lower" ON "public"."youtube_channels" USING "btree" ("lower"("handle"));
CREATE INDEX "idx_youtube_channels_name_lower" ON "public"."youtube_channels" USING "btree" ("lower"("channel_name"));
CREATE OR REPLACE TRIGGER "set_advice_guidance_user_id" BEFORE INSERT ON "public"."advice_guidance" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
CREATE OR REPLACE TRIGGER "set_congregation_members_user_id" BEFORE INSERT ON "public"."congregation_members" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
CREATE OR REPLACE TRIGGER "set_congregations_user_id" BEFORE INSERT ON "public"."congregations" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
CREATE OR REPLACE TRIGGER "set_counseling_sessions_user_id" BEFORE INSERT ON "public"."counseling_sessions" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
CREATE OR REPLACE TRIGGER "set_daily_devotionals_user_id" BEFORE INSERT ON "public"."daily_devotionals" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
CREATE OR REPLACE TRIGGER "set_daily_prayers_user_id" BEFORE INSERT ON "public"."daily_prayers" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
CREATE OR REPLACE TRIGGER "set_friends_user_id" BEFORE INSERT ON "public"."friends" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
CREATE OR REPLACE TRIGGER "set_sermon_series_user_id" BEFORE INSERT ON "public"."sermon_series" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
CREATE OR REPLACE TRIGGER "set_user_profiles_user_id" BEFORE INSERT ON "public"."user_profiles" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
CREATE OR REPLACE TRIGGER "set_users_user_id" BEFORE INSERT ON "public"."users" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id"();
ALTER TABLE ONLY "public"."bible_studies"
    ADD CONSTRAINT "bible_studies_congregation_id_fkey" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("congregation_id");
ALTER TABLE ONLY "public"."bible_study_lessons"
    ADD CONSTRAINT "bible_study_lessons_study_id_fkey" FOREIGN KEY ("study_id") REFERENCES "public"."bible_studies"("study_id");
ALTER TABLE ONLY "public"."check_ins"
    ADD CONSTRAINT "check_ins_checked_in_by_fkey" FOREIGN KEY ("checked_in_by") REFERENCES "public"."church_crm_profiles"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."check_ins"
    ADD CONSTRAINT "check_ins_congregation_id_fkey" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("congregation_id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."check_ins"
    ADD CONSTRAINT "check_ins_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."check_ins"
    ADD CONSTRAINT "check_ins_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."church_crm_profiles"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."church_crm_profiles"
    ADD CONSTRAINT "church_crm_profiles_congregation_id_fkey" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("congregation_id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."church_crm_profiles"
    ADD CONSTRAINT "church_crm_profiles_household_id_fkey" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."church_crm_profiles"
    ADD CONSTRAINT "church_crm_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."community_prayer_interactions"
    ADD CONSTRAINT "community_prayer_interactions_prayer_id_fkey" FOREIGN KEY ("prayer_id") REFERENCES "public"."community_prayers"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."community_prayer_interactions"
    ADD CONSTRAINT "community_prayer_interactions_praying_user_id_fkey" FOREIGN KEY ("praying_user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."community_prayers"
    ADD CONSTRAINT "community_prayers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."congregation_members"
    ADD CONSTRAINT "congregation_members_congregation_id_fkey" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("congregation_id");
ALTER TABLE ONLY "public"."content_feedback"
    ADD CONSTRAINT "content_feedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."event_volunteers"
    ADD CONSTRAINT "event_volunteers_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."event_volunteers"
    ADD CONSTRAINT "event_volunteers_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."volunteer_roles"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."event_volunteers"
    ADD CONSTRAINT "event_volunteers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_congregation_id_fkey" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("congregation_id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_organizer_id_fkey" FOREIGN KEY ("organizer_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."favorites"
    ADD CONSTRAINT "favorites_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."congregations"
    ADD CONSTRAINT "fk_leader_user" FOREIGN KEY ("leader_user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."households"
    ADD CONSTRAINT "households_congregation_id_fkey" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("congregation_id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."outlook_categories"
    ADD CONSTRAINT "outlook_categories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id");
ALTER TABLE ONLY "public"."outlook_categories"
    ADD CONSTRAINT "outlook_categories_outlook_id_fkey" FOREIGN KEY ("outlook_id") REFERENCES "public"."scriptural_outlooks"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."outlook_topics"
    ADD CONSTRAINT "outlook_topics_outlook_id_fkey" FOREIGN KEY ("outlook_id") REFERENCES "public"."scriptural_outlooks"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."outlook_topics"
    ADD CONSTRAINT "outlook_topics_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "public"."topics"("id");
ALTER TABLE ONLY "public"."pastoral_messages"
    ADD CONSTRAINT "pastoral_messages_congregation_id_fkey" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("congregation_id");
ALTER TABLE ONLY "public"."pastoral_notes"
    ADD CONSTRAINT "pastoral_notes_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."pastoral_notes"
    ADD CONSTRAINT "pastoral_notes_crm_profile_id_fkey" FOREIGN KEY ("crm_profile_id") REFERENCES "public"."church_crm_profiles"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."prayer_requests"
    ADD CONSTRAINT "prayer_requests_congregation_id_fkey" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("congregation_id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."prayer_requests"
    ADD CONSTRAINT "prayer_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."prompt_evaluations"
    ADD CONSTRAINT "prompt_evaluations_prompt_key_fkey" FOREIGN KEY ("prompt_key") REFERENCES "public"."system_prompts"("key");
ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."role_members"
    ADD CONSTRAINT "role_members_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."volunteer_roles"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."role_members"
    ADD CONSTRAINT "role_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."sermons"
    ADD CONSTRAINT "sermons_series_id_fkey" FOREIGN KEY ("series_id") REFERENCES "public"."sermon_series"("series_id");
ALTER TABLE ONLY "public"."sermons"
    ADD CONSTRAINT "sermons_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."system_logs"
    ADD CONSTRAINT "system_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."user_activities"
    ADD CONSTRAINT "user_activities_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."user_followed_categories"
    ADD CONSTRAINT "user_followed_categories_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."user_followed_topics"
    ADD CONSTRAINT "user_followed_topics_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."volunteer_roles"
    ADD CONSTRAINT "volunteer_roles_congregation_id_fkey" FOREIGN KEY ("congregation_id") REFERENCES "public"."congregations"("congregation_id") ON DELETE CASCADE;
CREATE POLICY "Enable users to view their own data only" ON "public"."sermons" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK (true);
CREATE POLICY "Everyone can read general devotionals" ON "public"."general_devotionals" FOR SELECT USING (true);
CREATE POLICY "Insert own prayers" ON "public"."community_prayers" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "Read approved prayers" ON "public"."community_prayers" FOR SELECT USING (("status" = 'approved'::"text"));
CREATE POLICY "Read own prayers" ON "public"."community_prayers" FOR SELECT USING (("auth"."uid"() = "user_id"));
CREATE POLICY "Service role full access" ON "public"."prompt_evaluations" USING (true) WITH CHECK (true);
CREATE POLICY "Service role has full access" ON "public"."system_prompts" USING (true) WITH CHECK (true);
CREATE POLICY "Users access owned content" ON "public"."daily_devotionals" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK (true);
CREATE POLICY "Users can delete their own subscriptions" ON "public"."push_subscriptions" FOR DELETE USING (("auth"."uid"() = "user_id"));
CREATE POLICY "Users can insert their own subscriptions" ON "public"."push_subscriptions" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));
CREATE POLICY "Users can manage their own favorites" ON "public"."favorites" USING (("auth"."uid"() = "user_id"));
ALTER TABLE "public"."admin_emails" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."app_options" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."community_prayer_interactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."community_prayers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."daily_devotionals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."daily_news_synopses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."favorites" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."general_devotionals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."outlook_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."outlook_topics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."prompt_evaluations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."push_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."scriptural_outlooks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sermon_preferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sermons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."system_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."system_prompts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."topics" ENABLE ROW LEVEL SECURITY;
ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT ALL ON FUNCTION "public"."handle_new_user_whitelist"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user_whitelist"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user_whitelist"() TO "service_role";
GRANT ALL ON FUNCTION "public"."set_user_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_user_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_user_id"() TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."admin_emails" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."admin_emails" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."admin_emails" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."advice_guidance" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."advice_guidance" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."advice_guidance" TO "service_role";
GRANT ALL ON SEQUENCE "public"."advice_guidance_advice_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."advice_guidance_advice_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."advice_guidance_advice_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."app_options" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."app_options" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."app_options" TO "service_role";
GRANT ALL ON SEQUENCE "public"."app_options_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."app_options_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."app_options_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."bible_reading_journeys" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."bible_reading_journeys" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."bible_reading_journeys" TO "service_role";
GRANT ALL ON SEQUENCE "public"."bible_reading_journeys_journey_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bible_reading_journeys_journey_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bible_reading_journeys_journey_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."bible_studies" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."bible_studies" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."bible_studies" TO "service_role";
GRANT ALL ON SEQUENCE "public"."bible_studies_study_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bible_studies_study_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bible_studies_study_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."bible_studies_study_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."bible_studies_study_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bible_studies_study_id_seq1" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."bible_study_lessons" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."bible_study_lessons" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."bible_study_lessons" TO "service_role";
GRANT ALL ON SEQUENCE "public"."bible_study_lessons_lesson_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bible_study_lessons_lesson_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bible_study_lessons_lesson_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."bible_study_lessons_lesson_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."bible_study_lessons_lesson_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bible_study_lessons_lesson_id_seq1" TO "service_role";
GRANT ALL ON SEQUENCE "public"."bible_study_lessons_study_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bible_study_lessons_study_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bible_study_lessons_study_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."categories" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."categories" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."categories" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."check_ins" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."check_ins" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."check_ins" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."church_crm_profiles" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."church_crm_profiles" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."church_crm_profiles" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."community_prayer_interactions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."community_prayer_interactions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."community_prayer_interactions" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."community_prayers" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."community_prayers" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."community_prayers" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."congregation_members" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."congregation_members" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."congregation_members" TO "service_role";
GRANT ALL ON SEQUENCE "public"."congregation_members_member_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."congregation_members_member_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."congregation_members_member_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."congregations" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."congregations" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."congregations" TO "service_role";
GRANT ALL ON SEQUENCE "public"."congregations_congregation_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."congregations_congregation_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."congregations_congregation_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contact" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contact" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."contact" TO "service_role";
GRANT ALL ON SEQUENCE "public"."contact_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contact_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contact_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."content_feedback" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."content_feedback" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."content_feedback" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."counseling_sessions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."counseling_sessions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."counseling_sessions" TO "service_role";
GRANT ALL ON SEQUENCE "public"."counseling_sessions_session_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."counseling_sessions_session_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."counseling_sessions_session_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."curated_tracks" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."curated_tracks" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."curated_tracks" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."daily_devotionals" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."daily_devotionals" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."daily_devotionals" TO "service_role";
GRANT ALL ON SEQUENCE "public"."daily_devotionals_devotional_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_devotionals_devotional_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_devotionals_devotional_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."daily_news_synopses" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."daily_news_synopses" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."daily_news_synopses" TO "service_role";
GRANT ALL ON SEQUENCE "public"."daily_news_synopses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_news_synopses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_news_synopses_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."daily_prayers" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."daily_prayers" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."daily_prayers" TO "service_role";
GRANT ALL ON SEQUENCE "public"."daily_prayers_prayer_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_prayers_prayer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_prayers_prayer_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."devotional_themes" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."devotional_themes" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."devotional_themes" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."event_volunteers" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."event_volunteers" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."event_volunteers" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."events" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."events" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."events" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."favorites" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."favorites" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."favorites" TO "service_role";
GRANT ALL ON SEQUENCE "public"."favorites_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."favorites_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."favorites_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."friends" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."friends" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."friends" TO "service_role";
GRANT ALL ON SEQUENCE "public"."friends_friendship_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."friends_friendship_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."friends_friendship_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."general_devotionals" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."general_devotionals" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."general_devotionals" TO "service_role";
GRANT ALL ON SEQUENCE "public"."general_devotionals_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."general_devotionals_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."general_devotionals_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."households" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."households" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."households" TO "service_role";
GRANT ALL ON SEQUENCE "public"."news_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."news_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."news_categories_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."topics" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."topics" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."topics" TO "service_role";
GRANT ALL ON SEQUENCE "public"."news_topics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."news_topics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."news_topics_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."outlook_categories" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."outlook_categories" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."outlook_categories" TO "service_role";
GRANT ALL ON SEQUENCE "public"."outlook_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."outlook_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."outlook_categories_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."outlook_topics" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."outlook_topics" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."outlook_topics" TO "service_role";
GRANT ALL ON SEQUENCE "public"."outlook_topics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."outlook_topics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."outlook_topics_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."pastoral_messages" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."pastoral_messages" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."pastoral_messages" TO "service_role";
GRANT ALL ON SEQUENCE "public"."pastoral_messages_message_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pastoral_messages_message_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pastoral_messages_message_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."pastoral_notes" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."pastoral_notes" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."pastoral_notes" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."prayer_requests" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."prayer_requests" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."prayer_requests" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."prompt_evaluations" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."prompt_evaluations" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."prompt_evaluations" TO "service_role";
GRANT ALL ON SEQUENCE "public"."prompt_evaluations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."prompt_evaluations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."prompt_evaluations_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."push_subscriptions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."push_subscriptions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."push_subscriptions" TO "service_role";
GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."recommended_videos" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."recommended_videos" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."recommended_videos" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."role_members" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."role_members" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."role_members" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."scriptural_outlooks" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."scriptural_outlooks" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."scriptural_outlooks" TO "service_role";
GRANT ALL ON SEQUENCE "public"."scriptural_outlooks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."scriptural_outlooks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."scriptural_outlooks_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sermon_preferences" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sermon_preferences" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sermon_preferences" TO "service_role";
GRANT ALL ON SEQUENCE "public"."sermon_preferences_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sermon_preferences_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sermon_preferences_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sermon_series" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sermon_series" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sermon_series" TO "service_role";
GRANT ALL ON SEQUENCE "public"."sermon_series_series_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sermon_series_series_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sermon_series_series_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sermons" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sermons" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."sermons" TO "service_role";
GRANT ALL ON SEQUENCE "public"."sermons_sermon_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sermons_sermon_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sermons_sermon_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."subscriptions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."subscriptions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."subscriptions" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."system_logs" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."system_logs" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."system_logs" TO "service_role";
GRANT ALL ON SEQUENCE "public"."system_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."system_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."system_logs_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."system_prompts" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."system_prompts" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."system_prompts" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_activities" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_activities" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_activities" TO "service_role";
GRANT ALL ON SEQUENCE "public"."user_activities_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_activities_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_activities_id_seq" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_followed_categories" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_followed_categories" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_followed_categories" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_followed_topics" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_followed_topics" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_followed_topics" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_profiles" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_profiles" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."user_profiles" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."users" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."users" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."users" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."volunteer_roles" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."volunteer_roles" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."volunteer_roles" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."whitelist" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."whitelist" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."whitelist" TO "service_role";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."youtube_channels" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."youtube_channels" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."youtube_channels" TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "service_role";
