alter table public.user_profiles
  add column if not exists notification_time_zone text not null default 'America/New_York';

create table if not exists public.notification_runtime_settings (
  category text primary key check (category in ('devotional', 'advice', 'news', 'church')),
  enabled boolean not null default false,
  rollout_stage text not null default 'dry_run' check (rollout_stage in ('dry_run', 'internal', '10', '50', '100')),
  send_local_time time not null,
  quiet_hours_start time not null default '21:00',
  quiet_hours_end time not null default '08:00',
  minimum_spacing_minutes integer not null default 360 check (minimum_spacing_minutes >= 0),
  stage_started_at timestamptz not null default now(),
  last_gate_evaluated_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.notification_runtime_settings (category, enabled, rollout_stage, send_local_time)
values
  ('devotional', true, 'internal', '09:00'),
  ('advice', true, 'internal', '15:00'),
  ('news', false, 'dry_run', '19:00'),
  ('church', false, 'dry_run', '12:00')
on conflict (category) do nothing;

create table if not exists public.notification_campaigns (
  id uuid primary key default gen_random_uuid(),
  category text not null check (category in ('devotional', 'advice', 'news', 'church')),
  campaign_key text not null unique,
  campaign_date date not null,
  content_type text,
  content_id text,
  copy_variant smallint not null default 1 check (copy_variant between 1 and 4),
  scheduled_local_time time not null,
  rollout_stage text not null check (rollout_stage in ('dry_run', 'internal', '10', '50', '100')),
  rollout_percentage smallint not null default 0 check (rollout_percentage between 0 and 100),
  status text not null default 'scheduled' check (status in ('draft', 'scheduled', 'sending', 'complete', 'halted', 'cancelled')),
  emergency_exempt boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notification_campaigns_category_date_idx
  on public.notification_campaigns (category, campaign_date desc);

create table if not exists public.notification_deliveries (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.notification_campaigns(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  content_id text,
  local_date date not null,
  channel text not null check (channel in ('native', 'web')),
  status text not null check (status in ('planned', 'attempted', 'accepted', 'failed', 'opened', 'suppressed')),
  scheduled_for timestamptz not null,
  attempted_at timestamptz,
  accepted_at timestamptz,
  opened_at timestamptz,
  provider_message_id text,
  failure_code text,
  copy_variant smallint not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, user_id)
);

create unique index if not exists notification_deliveries_daily_content_idx
  on public.notification_deliveries (user_id, category, coalesce(content_id, ''), local_date);
create index if not exists notification_deliveries_recent_user_idx
  on public.notification_deliveries (user_id, accepted_at desc);
create index if not exists notification_deliveries_provider_idx
  on public.notification_deliveries (provider_message_id)
  where provider_message_id is not null;

create table if not exists public.notification_preference_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  enabled boolean not null,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_dispatch_runs (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  dry_run boolean not null default false,
  rollout_stage text not null,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists notification_dispatch_runs_category_time_idx
  on public.notification_dispatch_runs (category, created_at desc);
create index if not exists notification_preference_events_category_time_idx
  on public.notification_preference_events (category, created_at desc);

create or replace function public.capture_notification_preference_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  category_name text;
  old_value boolean;
  new_value boolean;
begin
  foreach category_name in array array['devotionals', 'advice', 'news', 'announcements'] loop
    old_value := case when old.user_preferences->'notifications' ? category_name
      then (old.user_preferences->'notifications'->>category_name)::boolean else null end;
    new_value := case when new.user_preferences->'notifications' ? category_name
      then (new.user_preferences->'notifications'->>category_name)::boolean else null end;
    if new_value is distinct from old_value and new_value is not null then
      insert into public.notification_preference_events (user_id, category, enabled)
      values (new.user_id, case category_name when 'devotionals' then 'devotional' when 'announcements' then 'church' else category_name end, new_value);
    end if;
  end loop;
  return new;
end;
$$;

drop trigger if exists capture_notification_preference_changes on public.user_profiles;
create trigger capture_notification_preference_changes
after update of user_preferences on public.user_profiles
for each row execute function public.capture_notification_preference_changes();

alter table public.notification_runtime_settings enable row level security;
alter table public.notification_campaigns enable row level security;
alter table public.notification_deliveries enable row level security;
alter table public.notification_preference_events enable row level security;
alter table public.notification_dispatch_runs enable row level security;

revoke all on public.notification_runtime_settings from anon, authenticated;
revoke all on public.notification_campaigns from anon, authenticated;
revoke all on public.notification_deliveries from anon, authenticated;
revoke all on public.notification_preference_events from anon, authenticated;
revoke all on public.notification_dispatch_runs from anon, authenticated;
grant all on public.notification_runtime_settings to service_role;
grant all on public.notification_campaigns to service_role;
grant all on public.notification_deliveries to service_role;
grant all on public.notification_preference_events to service_role;
grant all on public.notification_dispatch_runs to service_role;
